parameters:

    qb_repo.database:
        database: %database_name%
        host: %database_host%
        driver: mysql
        username: %database_user%
        password: %database_password%

    #qb_repo.repository.autoload_namespace:
        #- [Quallsbenson\Repository]

    #qb_repo.repository_initializer.autoload_namespace:
        #- [Quallsbenson\RepositoryInitializer]

    #qb_repo.model.autoload_namespace:
        #- [Quallsbenson\Model]

    #qb_repo.generator:
        #template_path: Path\to\templates
        #model_namespace: Quallsbenson\Model
        #repository_namespace: Quallsbenson\Respository
        #repository_initializer_namespace: Quallsbenson\RepositoryInitializer


services:
    qb_repo.manager:
        class: Quallsbenson\Symfony\RepositoryManager
        arguments: ["@qb_repo.database.manager"]
    qb_repo.database.manager:
        class: Quallsbenson\Repository\RepositoryManagerBundle\Database\DatabaseManager
        calls:
            - [setConnectionParameters, [%qb_repo.database%]]
    qb_repo.manager.command:
        class: Quallsbenson\Repository\RepositoryManagerBundle\Command\GenerateCommand
        calls:
            - [setConfigurationOptions, [%qb_repo.generator%]]
        tags:
            - { name: console.command }